### ISSUE TITLE
Run on time based trigger

### ISSUE THREAD

**Issue by man-over-board** [Max-Makhrov/range2image#3]
Script is perfect for generating images from within the sheets document itself, but is it possible to adjust it to be able to run on a trigger?

I think this would be difficult as much of the html based script would need to be moved into the .gs, which may not be possible?

**Comment by Max-Makhrov** [comment]
> Script is perfect for generating images from within the sheets document itself, but is it possible to adjust it to be able to run on a trigger?
> 
> I think this would be difficult as much of the html based script would need to be moved into the .gs, which may not be possible?

Hi,

This question bothers me too, for now I did not try, but possibly we could play around with `UrlFetch` to handle that. 

Here Justin shows an example of extending scipts possibilities:

[https://justin.poehnelt.com/posts/apps-script-runtime-limitations-wintercg/](https://justin.poehnelt.com/posts/apps-script-runtime-limitations-wintercg/)

I'd be glad with any help here.

**Comment by man-over-board** [comment]
Yes, I think it would be a lot of slowly working through line by line to see if there are apps script alternatives for things.

I started taking a look at it yesterday, but this is new stuff for me. Will continue to try and chip away at it.

**Comment by vetriselvan98** [comment]
Hi @man-over-board  - grinding over the same issue. Please do share if you have found a solution! :)

**Comment by man-over-board** [comment]
In the end I went a different route - mostly because of my use case. 

I was trying to take snapshots of chats with some surrounding cells with relevant information. I found I could convert chart objects to images (which requires using slides as an in-between, weirdly...). I set this up to auto generate all the charts I wanted on a schedule. 

https://tanaikech.github.io/2020/06/23/workaround-correctly-exporting-charts-on-google-spreadsheet-as-images-using-google-apps-script/

**Comment by Max-Makhrov** [comment]
The issue is resolved, see documentation for version 2

https://github.com/Max-Makhrov/range2image

**Comment by Max-Makhrov** [comment]
Now you can set it to a trigger and run daily.
The last update makes all conversions inside App Script.

Other good news:
 * fully supports ES-5 engine
 * Minimal scopes required

Installation:
 1. Add Drive App external service
 2. Go to manifest and (appscript.json) and change the Drive version to V3.
